services:
  frontend:
    build:
      context: ./frontend # フロントエンドプロジェクトのディレクトリ
      dockerfile: Dockerfile # 使用するDockerfile
    volumes:
      - ./frontend:/app # フロントエンドのソースコードの変更をコンテナに即時反映
      - /app/node_modules # node_modulesを永続化するためのボリューム
    environment: # Dockerコンテナ内で利用可能な環境変数を設定する
      - NODE_ENV=development # 開発環境として設定
      - FAST_REFRESH=true # Viteの高速リフレッシュ機能を有効化
      - VITE_ENDPOINT=$ENDPOINT # APIエンドポイントのURL
      - VITE_API_VERSION=$API_VERSION # APIバージョン
    command: npm run dev # アプリケーションの実行コマンドを指定する
    ports:
      - "3000:3000" # [ホストのポート番号]：[コンテナのポート番号]
    depends_on:
      - backend # backendサービスが起動した後にこのサービスを起動する
    restart: always # コンテナが停止した場合に自動的に再起動
    stdin_open: true # 標準入力を開いておく
    tty: true # 端末を有効化

  backend:
    build: # backend の Dockerfile があるパス
      context: ./backend # バックエンドプロジェクトのディレクトリ
      dockerfile: Dockerfile # 使用するDockerfile
    volumes:
      - ./backend:/app # バックエンドのソースコードの変更をコンテナに即時反映
    ports:
      - "8080:8080" # [ホストのポート番号]：[コンテナのポート番号]
    environment: # サービスのコンテナに環境変数を設定
      DB_HOST: db # データベースホスト名
      DB_USER: ${DB_USER} # データベースユーザー名
      DB_PASSWORD: ${DB_PASSWORD} # データベースパスワード
      DB_NAME: ${DB_NAME} # データベース名
    depends_on:
      - db # 依存関係の定義
    restart: always # コンテナが停止した場合に自動的に再起動

  # データベースサービス
  db:
    image: mysql:8.4 # 使用するMySQLイメージ
    volumes: # コンテナの外部に保管する
      - mysql-data-dev:/var/lib/mysql # データベースデータを永続化するボリューム
    environment: # サービスのコンテナに環境変数を設定
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DEV} # MySQLルートパスワード
      MYSQL_DATABASE: ${MYSQL_DATABASE_DEV} # データベース名
      MYSQL_USER: ${MYSQL_USER_DEV} # データベースユーザー名
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_DEV} # データベースパスワード
    ports:
      - "3306:3306" # [ホストのポート番号]：[コンテナのポート番号]
    restart: always # コンテナが停止した場合に自動的に再起動

# ボリュームの定義
volumes:
  mysql-data-dev: # db の volume の名前を定義
