# .github/workflows/integration-tests.yml
name: Integration Tests

on:
  pull_request:
    paths:
      - 'backend/test/integration/controller/memo_controller_test.go'
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
  workflow_dispatch: # 手動トリガー

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        volumes:
          - ./mysql/init:/docker-entrypoint-initdb.d
        options: >-
          --health-cmd "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: s3,sqs,dynamodb
          DEFAULT_REGION: ap-northeast-1
          LS_LOG: trace
        volumes:
          - ./localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
        options: >-
          --health-cmd "localstack wait -t 30"
          --health-interval 10s

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localhost:4566
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Initialize submodules
        run: git submodule update --init

      - name: Run integration tests
        run: |
          go test -v ./backend/test/integration/controller/memo_controller_test.go \
            -tags=integration \
            -coverprofile=coverage.out
