name: Integration Tests

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
  workflow_dispatch: # 手動トリガー

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Initialize submodules
        run: git submodule update --init

      - name: Run integration tests
        run: |
          go test -v ./backend/test/integration/... \
            -tags=integration \
            -coverprofile=coverage.out
